export const subjects = [
  { value: 'magyir', label: 'Magyar nyelv és irodalom' },
  { value: 'mat', label: 'Matematika' },
  { value: 'tort', label: 'Történelem' },
  { value: 'angol', label: 'Angol nyelv' },
  { value: 'nemet', label: 'Német nyelv' },
  { value: 'inf', label: 'Informatika' },
  { value: 'infoism', label: 'Informatikai ismeretek' },
  { value: 'ker', label: 'Kereskedelmi ismeretek' },
  { value: 'kozg', label: 'Közgazdasági ismeretek' },
  { value: 'fiz', label: 'Fizika' },
  { value: 'kem', label: 'Kémia' },
  { value: 'bio', label: 'Biológia' },
  { value: 'fldr', label: 'Földrajz' },
]
